2019-03-27 12:00:39 -0 - [main] ERROR com.capgemini.bankapp.client.BankAccountCui  -Exception: 
 com.capgemini.bankapp.exception.LowBalanceException: Low Balance unable to process withdraw
	at com.capgemini.bankapp.service.impl.BankAccountServiceImpl.withdraw(BankAccountServiceImpl.java:34)
	at com.capgemini.bankapp.client.BankAccountCui.main(BankAccountCui.java:60)
2019-03-27 12:26:21 -0 - [main] ERROR com.capgemini.bankapp.client.BankAccountCui  -com.capgemini.bankapp.exception.LowBalanceException: Low Balance unable to process withdraw
 2019-03-28 11:35:07 -0 - [main] ERROR com.capgemini.bankapp.util.DbUtil  -SQLException
 com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Connection.close() has already been called. Invalid operation in this state.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:985)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.ConnectionImpl.getMutex(ConnectionImpl.java:3015)
	at com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1521)
	at com.capgemini.bankapp.util.DbUtil.commit(DbUtil.java:39)
	at com.capgemini.bankapp.service.impl.BankAccountServiceImpl.addNewBankAccount(BankAccountServiceImpl.java:90)
	at com.capgemini.bankapp.client.BankAccountCui.main(BankAccountCui.java:51)
2019-03-28 11:43:53 -1 - [main] ERROR com.capgemini.bankapp.util.DbUtil  -SQLException
 com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Connection.close() has already been called. Invalid operation in this state.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:985)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.ConnectionImpl.getMutex(ConnectionImpl.java:3015)
	at com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1521)
	at com.capgemini.bankapp.util.DbUtil.commit(DbUtil.java:39)
	at com.capgemini.bankapp.service.impl.BankAccountServiceImpl.deleteBankAccount(BankAccountServiceImpl.java:80)
	at com.capgemini.bankapp.client.BankAccountCui.main(BankAccountCui.java:108)
2019-03-28 11:45:41 -0 - [main] ERROR com.capgemini.bankapp.util.DbUtil  -SQLException
 com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Connection.close() has already been called. Invalid operation in this state.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:985)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.ConnectionImpl.getMutex(ConnectionImpl.java:3015)
	at com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1521)
	at com.capgemini.bankapp.util.DbUtil.commit(DbUtil.java:41)
	at com.capgemini.bankapp.service.impl.BankAccountServiceImpl.deleteBankAccount(BankAccountServiceImpl.java:80)
	at com.capgemini.bankapp.client.BankAccountCui.main(BankAccountCui.java:108)
2019-03-28 11:47:18 -0 - [main] ERROR com.capgemini.bankapp.util.DbUtil  -SQLException
 com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Connection.close() has already been called. Invalid operation in this state.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:985)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.ConnectionImpl.getMutex(ConnectionImpl.java:3015)
	at com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1521)
	at com.capgemini.bankapp.util.DbUtil.commit(DbUtil.java:41)
	at com.capgemini.bankapp.service.impl.BankAccountServiceImpl.deleteBankAccount(BankAccountServiceImpl.java:80)
	at com.capgemini.bankapp.client.BankAccountCui.main(BankAccountCui.java:108)
